TIE_BREAKER_QUESTIONS = [
    # ---------------- R-I ----------------
    {"number": 31, "pair": "R-I", "question": "Which activity appeals to you more?",
     "options": {"A": {"text": "Fixing or building something using tools", "riasec": "R"},
                 "B": {"text": "Analyzing data to understand a problem", "riasec": "I"}}},
    {"number": 32, "pair": "R-I", "question": "Which task would you choose?",
     "options": {"A": {"text": "Working with machines or equipment", "riasec": "R"},
                 "B": {"text": "Conducting research to find answers", "riasec": "I"}}},
    {"number": 33, "pair": "R-I", "question": "Which role feels more natural?",
     "options": {"A": {"text": "Repairing or assembling mechanical items", "riasec": "R"},
                 "B": {"text": "Solving theoretical or analytical problems", "riasec": "I"}}},

    # ---------------- R-A ----------------
    {"number": 34, "pair": "R-A", "question": "Which activity fits you better?",
     "options": {"A": {"text": "Building or assembling physical objects", "riasec": "R"},
                 "B": {"text": "Creating an artistic design or concept", "riasec": "A"}}},
    {"number": 35, "pair": "R-A", "question": "Which work would you prefer?",
     "options": {"A": {"text": "Repairing mechanical items", "riasec": "R"},
                 "B": {"text": "Expressing ideas through creative art", "riasec": "A"}}},
    {"number": 36, "pair": "R-A", "question": "Which project excites you more?",
     "options": {"A": {"text": "Constructing or fixing mechanical devices", "riasec": "R"},
                 "B": {"text": "Designing an original artwork or concept", "riasec": "A"}}},

    # ---------------- R-S ----------------
    {"number": 37, "pair": "R-S", "question": "Which appeals to you more?",
     "options": {"A": {"text": "Working independently on hands-on tasks", "riasec": "R"},
                 "B": {"text": "Helping others solve their problems", "riasec": "S"}}},
    {"number": 38, "pair": "R-S", "question": "Which situation suits you?",
     "options": {"A": {"text": "Using tools to complete practical work", "riasec": "R"},
                 "B": {"text": "Providing guidance or support to people", "riasec": "S"}}},
    {"number": 39, "pair": "R-S", "question": "Which task feels more rewarding?",
     "options": {"A": {"text": "Building or repairing physical items", "riasec": "R"},
                 "B": {"text": "Assisting someone in learning or solving issues", "riasec": "S"}}},

    # ---------------- R-E ----------------
    {"number": 40, "pair": "R-E", "question": "Which would you rather do?",
     "options": {"A": {"text": "Operate tools or machinery", "riasec": "R"},
                 "B": {"text": "Lead a team to achieve goals", "riasec": "E"}}},
    {"number": 41, "pair": "R-E", "question": "Which role fits you more?",
     "options": {"A": {"text": "Performing physical or mechanical tasks", "riasec": "R"},
                 "B": {"text": "Persuading others and influencing decisions", "riasec": "E"}}},
    {"number": 42, "pair": "R-E", "question": "Which activity would you choose?",
     "options": {"A": {"text": "Fixing or maintaining machinery", "riasec": "R"},
                 "B": {"text": "Organizing and motivating a team", "riasec": "E"}}},

    # ---------------- R-C ----------------
    {"number": 43, "pair": "R-C", "question": "Which activity do you prefer?",
     "options": {"A": {"text": "Doing practical work involving tools", "riasec": "R"},
                 "B": {"text": "Organizing documents or structured information", "riasec": "C"}}},
    {"number": 44, "pair": "R-C", "question": "Which type of work matches you?",
     "options": {"A": {"text": "Repairing or assembling items", "riasec": "R"},
                 "B": {"text": "Following defined procedures accurately", "riasec": "C"}}},
    {"number": 45, "pair": "R-C", "question": "Which task would you enjoy more?",
     "options": {"A": {"text": "Building, fixing, or operating equipment", "riasec": "R"},
                 "B": {"text": "Maintaining organized records or systems", "riasec": "C"}}},

    # ---------------- I-A ----------------
    {"number": 46, "pair": "I-A", "question": "Which task interests you more?",
     "options": {"A": {"text": "Solving scientific or analytical problems", "riasec": "I"},
                 "B": {"text": "Creating artistic or expressive work", "riasec": "A"}}},
    {"number": 47, "pair": "I-A", "question": "Which activity suits you better?",
     "options": {"A": {"text": "Studying theories and concepts", "riasec": "I"},
                 "B": {"text": "Designing or developing creative content", "riasec": "A"}}},
    {"number": 48, "pair": "I-A", "question": "Which project would you enjoy more?",
     "options": {"A": {"text": "Researching or analyzing complex problems", "riasec": "I"},
                 "B": {"text": "Creating an original artistic piece", "riasec": "A"}}},

    # ---------------- I-S ----------------
    {"number": 49, "pair": "I-S", "question": "Which work style do you prefer?",
     "options": {"A": {"text": "Researching complex ideas alone", "riasec": "I"},
                 "B": {"text": "Helping or teaching people", "riasec": "S"}}},
    {"number": 50, "pair": "I-S", "question": "What would you choose?",
     "options": {"A": {"text": "Analyzing data or patterns", "riasec": "I"},
                 "B": {"text": "Working closely with people to support them", "riasec": "S"}}},
    {"number": 51, "pair": "I-S", "question": "Which activity is more satisfying?",
     "options": {"A": {"text": "Solving theoretical or scientific challenges", "riasec": "I"},
                 "B": {"text": "Providing guidance or assistance to others", "riasec": "S"}}},

    # ---------------- I-E ----------------
    {"number": 52, "pair": "I-E", "question": "Which activity feels more natural?",
     "options": {"A": {"text": "Conducting analysis or experiments", "riasec": "I"},
                 "B": {"text": "Leading and influencing others", "riasec": "E"}}},
    {"number": 53, "pair": "I-E", "question": "What would you prefer?",
     "options": {"A": {"text": "Working with data and theories", "riasec": "I"},
                 "B": {"text": "Taking charge of group tasks or decisions", "riasec": "E"}}},
    {"number": 54, "pair": "I-E", "question": "Which task would you enjoy more?",
     "options": {"A": {"text": "Researching scientific or technical problems", "riasec": "I"},
                 "B": {"text": "Leading a team to achieve goals", "riasec": "E"}}},

    # ---------------- I-C ----------------
    {"number": 55, "pair": "I-C", "question": "Which activity appeals to you?",
     "options": {"A": {"text": "Exploring scientific or technical ideas", "riasec": "I"},
                 "B": {"text": "Organizing structured information", "riasec": "C"}}},
    {"number": 56, "pair": "I-C", "question": "Which task suits you more?",
     "options": {"A": {"text": "Investigating and discovering new knowledge", "riasec": "I"},
                 "B": {"text": "Maintaining accuracy in data systems", "riasec": "C"}}},
    {"number": 57, "pair": "I-C", "question": "Which role would you prefer?",
     "options": {"A": {"text": "Conducting independent research", "riasec": "I"},
                 "B": {"text": "Systematically organizing and reviewing information", "riasec": "C"}}},

    # ---------------- A-S ----------------
    {"number": 58, "pair": "A-S", "question": "Which activity feels more engaging?",
     "options": {"A": {"text": "Creating expressive or artistic materials", "riasec": "A"},
                 "B": {"text": "Supporting or counseling others", "riasec": "S"}}},
    {"number": 59, "pair": "A-S", "question": "What interests you more?",
     "options": {"A": {"text": "Working on creative projects", "riasec": "A"},
                 "B": {"text": "Helping people grow or improve", "riasec": "S"}}},
    {"number": 60, "pair": "A-S", "question": "Which task excites you more?",
     "options": {"A": {"text": "Designing artistic work or performances", "riasec": "A"},
                 "B": {"text": "Mentoring or coaching individuals", "riasec": "S"}}},

    # ---------------- A-E ----------------
    {"number": 61, "pair": "A-E", "question": "Which activity do you prefer?",
     "options": {"A": {"text": "Expressing ideas through creativity", "riasec": "A"},
                 "B": {"text": "Leading or persuading others", "riasec": "E"}}},
    {"number": 62, "pair": "A-E", "question": "Which suits you more?",
     "options": {"A": {"text": "Focusing on originality and artistic work", "riasec": "A"},
                 "B": {"text": "Making decisions and influencing people", "riasec": "E"}}},
    {"number": 63, "pair": "A-E", "question": "Which project excites you more?",
     "options": {"A": {"text": "Creating a unique piece of art or design", "riasec": "A"},
                 "B": {"text": "Organizing and leading a team", "riasec": "E"}}},

    # ---------------- A-C ----------------
    {"number": 64, "pair": "A-C", "question": "Which environment fits you better?",
     "options": {"A": {"text": "A flexible, creative workspace", "riasec": "A"},
                 "B": {"text": "A structured and organized setting", "riasec": "C"}}},
    {"number": 65, "pair": "A-C", "question": "Which task would you choose?",
     "options": {"A": {"text": "Designing original creative work", "riasec": "A"},
                 "B": {"text": "Managing orderly information", "riasec": "C"}}},
    {"number": 66, "pair": "A-C", "question": "Which activity would you enjoy more?",
     "options": {"A": {"text": "Developing innovative artistic concepts", "riasec": "A"},
                 "B": {"text": "Organizing and systematizing work processes", "riasec": "C"}}},

    # ---------------- S-E ----------------
    {"number": 67, "pair": "S-E", "question": "Which role fits you more?",
     "options": {"A": {"text": "Supporting people through guidance", "riasec": "S"},
                 "B": {"text": "Motivating or leading a group", "riasec": "E"}}},
    {"number": 68, "pair": "S-E", "question": "Which activity appeals to you?",
     "options": {"A": {"text": "Teaching or mentoring individuals", "riasec": "S"},
                 "B": {"text": "Convincing others to follow a plan", "riasec": "E"}}},
    {"number": 69, "pair": "S-E", "question": "Which task would you prefer?",
     "options": {"A": {"text": "Helping others develop skills", "riasec": "S"},
                 "B": {"text": "Leading a team to achieve results", "riasec": "E"}}},

    # ---------------- S-C ----------------
    {"number": 70, "pair": "S-C", "question": "What work appeals to you more?",
     "options": {"A": {"text": "Helping people with personal issues", "riasec": "S"},
                 "B": {"text": "Handling organized administrative tasks", "riasec": "C"}}},
    {"number": 71, "pair": "S-C", "question": "Which task suits your style?",
     "options": {"A": {"text": "Working with people to support them", "riasec": "S"},
                 "B": {"text": "Maintaining detailed records or systems", "riasec": "C"}}},
    {"number": 72, "pair": "S-C", "question": "Which activity feels more satisfying?",
     "options": {"A": {"text": "Assisting others to solve problems", "riasec": "S"},
                 "B": {"text": "Organizing and tracking structured information", "riasec": "C"}}},

    # ---------------- E-C ----------------
    {"number": 73, "pair": "E-C", "question": "Which activity suits you better?",
     "options": {"A": {"text": "Leading initiatives and making decisions", "riasec": "E"},
                 "B": {"text": "Following structured workflows", "riasec": "C"}}},
    {"number": 74, "pair": "E-C", "question": "Which role do you prefer?",
     "options": {"A": {"text": "Persuading others and directing actions", "riasec": "E"},
                 "B": {"text": "Organizing and maintaining detailed systems", "riasec": "C"}}},
    {"number": 75, "pair": "E-C", "question": "Which task is more appealing?",
     "options": {"A": {"text": "Leading and influencing team decisions", "riasec": "E"},
                 "B": {"text": "Implementing structured processes efficiently", "riasec": "C"}}},
]
